DOCSP-41975: Retrieve data
mongodb/docs-php-library pull request #102
Opened 2024-08-12 16:11 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-php-library/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-41975
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-08-12 19:50 UTC, jordan-smith721 approved these changes
LGTM w/ a couple comments

2024-08-16 10:08 UTC, GromNaN requested changes

2024-08-16 15:35 UTC, norareidy commented on source/includes/read/retrieve.php
> +$results = $collection->find(['number_of_employees' => 1000], $options);
Just for emphasis on the options, but I added some code highlighting instead

2024-08-16 17:58 UTC, GromNaN commented on source/includes/read/retrieve.php
> +// end-modify
```suggestion
// end-modify

```

2024-08-19 09:05 UTC, GromNaN approved these changes

2024-08-19 09:05 UTC, GromNaN commented on snooty.toml
> +api = "https://www.mongodb.com/docs/php-library/current/reference"
```suggestion
api = "https://www.mongodb.com/docs/php-library/current/reference"

```

2024-08-19 14:23 UTC, GromNaN approved these changes

2024-08-19 14:26 UTC, merged