DOCSP-41978: Count documents
mongodb/docs-php-library pull request #108
Opened 2024-08-19 20:24 UTC by norareidy

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-php-library/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-41978
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/php-library/DOCSP-41978-count/read/count/

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-08-19 20:46 UTC, norareidy commented on source/read/count.txt
> +To learn more about specifying a query, see the :ref:`php-specify-query` guide.
Note: link broken until #103 is merged

2024-08-19 21:01 UTC, rustagir requested changes
a few small improvements!

2024-08-19 21:01 UTC, rustagir commented on source/read/count.txt
> +the ``estimatedDocumentCount()`` method. The method estimates the amount of
S: in other method references, you include the class that the method is part of

2024-08-19 21:01 UTC, rustagir commented on source/read/count.txt
> +to run for a maximum of ``1000`` milliseconds:
```suggestion
The following example uses the ``estimatedDocumentCount()`` method to return an
estimate of the number of documents in the collection and sets a timeout of
``1000`` milliseconds on the operation:
```

2024-08-20 15:17 UTC, rustagir approved these changes

2024-08-29 14:05 UTC, GromNaN approved these changes

2024-08-29 20:10 UTC, merged