DOCSP-44903 Shorten TOC Labels
mongodb/docs-php-library pull request #176
Opened 2024-10-31 20:55 UTC by lindseymoore

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-php-library/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-44903>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-10-31 22:03 UTC, lindseymoore commented
@mongoKart How do you feel about keeping toc titles action-oriented (starting with action verb)? Makes titles long, but I tried to keep it action-oriented if the title didn't take up more than two lines. Let me know!

2024-11-01 13:39 UTC, mongoKart commented
> @mongoKart How do you feel about keeping toc titles action-oriented (starting with action verb)? Makes titles long, but I tried to keep it action-oriented if the title didn't take up more than two lines. Let me know!

Good question! When I started, I was told to keep headings task-oriented, but I don't know if we're still doing that and if it also applies to the TOC.

@sarahemlin Do you have thoughts on this from an IA/SEO perspective?

2024-11-01 14:47 UTC, mongoKart approved these changes
LGTM w/ a couple suggestions

2024-11-01 14:47 UTC, mongoKart commented on source/data-formats.txt
> +   BSON Data </data-formats/modeling-bson-data>
Could just be BSON

```suggestion
   BSON </data-formats/modeling-bson-data>
```

2024-11-01 14:47 UTC, mongoKart commented on source/reference/result-classes.txt
> +   BulkWriteResult </reference/class/MongoDBBulkWriteResult>
great change for this group

2024-11-01 14:47 UTC, mongoKart commented on source/write.txt
> +   Perform a Transaction </write/transaction>
S: "Perform" is a generic enough verb that it might not be adding much here

```suggestion
   Transactions </write/transaction>
```

2024-11-01 22:29 UTC, sarahemlin requested changes

2024-11-01 22:29 UTC, sarahemlin commented on source/get-started.txt
> +   Download and Install </get-started/download-and-install/>
@mongoKart ampersand for TOC labels is OK

2024-11-01 22:29 UTC, sarahemlin commented on source/index.txt
> +   Databases and Collections </databases-collections>
ampersand here, too

2024-11-07 15:02 UTC, sarahemlin approved these changes

2024-11-07 23:02 UTC, merged